name: Daily Commit
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Get random user email
      id: random_user
      run: |
         PAGE=$((RANDOM % 1000 + 1))
         RANDOM_USERNAME=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/users?per_page=100&page=$PAGE" | jq -r '.[] | select(.login != null) | .login' | shuf -n 1)
         if [ -z "$RANDOM_USERNAME" ]; then
          RANDOM_USERNAME="github-actions[bot]"
         fi
         RANDOM_USER_EMAIL="${RANDOM_USERNAME}@users.noreply.github.com"
         echo "username=$RANDOM_USERNAME" >> $GITHUB_OUTPUT
         echo "email=$RANDOM_USER_EMAIL" >> $GITHUB_OUTPUT
    - name: Create daily commit
      run: |
        git pull
        COMMIT_MESSAGE="Daily commit $(date)
        Co-authored-by: ${{ steps.random_user.outputs.username }} <${{ steps.random_user.outputs.email }}>"
        echo "Commit message:"
        echo "$COMMIT_MESSAGE"
        DATE=$(date +%Y-%m-%d)
        echo "$COMMIT_MESSAGE" > "commit_$DATE.txt"
        git add commit_$DATE.txt
        git commit -m "$COMMIT_MESSAGE"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
